export {default as Home} from './Home';
export {default as homeStyles} from './home.css';
export {default as Section1} from './Section1'
export {default as section1Styles} from './section1.css'
export {default as Section2} from './Section2';
export {default as section2Styles} from './section2.css';
export {default as Section3} from './Section3';
export {default as section3Styles} from './section3.css';
export {default as Section4} from './Section4';
export {default as section4Styles} from './section4.css';
export {default as Section5} from './Section5';
export {default as section5Styles} from './section5.css';
export {default as Section6} from './Section6';
export {default as section6Styles} from './section6.css';
export {default as Section7} from './Section7';
export {default as section7Styles} from './section7.css';
export {default as Section8} from './Section8';
export {default as section8Styles} from './section8.css';
